### ISSUE TITLE
todo for submission

### ISSUE THREAD

**Issue by dyurovsky** [ashleychuikay/animalgame#1]
- [x]  fill out submission checklist
- [x] check that we've met all of the style requirements
- [x] add model details to SI
- [x] center statement of relevance
- [x] renumber databrary participants
- [x] final tidy of repo
- [x] make masked version?
- [x] post to arxiv
